#+TITLE: My Website
#+AUTHOR: guy

#+TITLE: My Website
#+AUTHOR: guy

#+BEGIN_EXPORT html
<div class="profile-image">
  <canvas id="slime-canvas" width="600" height="600"></canvas>
</div>

<script type="module">
  import Slime from "/js/Slime.js";

  const img = new Image();
  var d = new Date(); 
  var sec = d.getSeconds();
  img.src = "/papers/id2.jpeg";

  img.onload = () => {
    const canvas = document.getElementById("slime-canvas");
    const ctx = canvas.getContext("2d");

    const W = canvas.width;
    const H = canvas.height;

    const tmp = document.createElement("canvas");
    tmp.width = W;
    tmp.height = H;
    const tctx = tmp.getContext("2d");

    tctx.drawImage(img, 0, 0, W, H);
    const srcData = tctx.getImageData(0, 0, W, H);

    const algo = new Slime();
    algo.setSourceImage({ data: srcData.data, width: W, height: H });

    const params = {
      blur: 7,
      num_agents: 100000,
      sensor_angle: 0.3,
      sensor_dist: 7,
      turn_speed: 0.8,
      move_speed: 1.2,
      decay_rate: sec * 0.003,
      deposit_amount: 0.09,
      brightness_influence: sec,
    };

    let frame = 0;
    const slowFactor = 8;

    function step() {
      if ((frame < 11 || frame > 50) && frame % slowFactor == 0) {
	    algo.findBestRectangle(params);
	    if ((frame >= 12 || frame == 8) && frame % slowFactor == 0) {
            	algo.render(ctx, params);
	    }
      }
      frame++;
      requestAnimationFrame(step);
    }
    step();
  };
</script>
#+END_EXPORT


* Welcome

I am a PhD candidate at the University of Edinburgh in the MLSystems CDT, working on program synthesis under the supervision of [[https://polgreen.github.io/][Elizabeth Polgreen]].

My [[file:cv.org][CV]].


* Papers

- Debugging into Existence with Program Synthesis [link] [[[file:../papers/desynt.pdf][paper]]] \\
  *Guy Frankel*, Shay Segal and Hila Peleg. VL/HCC 2025.


- Unlocking Hardware Verification with Oracle Guided Synthesis [link] \\
  Leiqi Ye, *Guy Frankel*, Yixuan Li, Jianyi Cheng and Elizabeth Polgreen. FMCAD 2025.


- Challenges in Modeling and Unmodeling Complex Reactive Systems: Interaction Networks, Reaction to Emergent Effects, Reactive Rule Composition, and Multiple Time Scales [[[https://link.springer.com/chapter/10.1007/978-3-031-66339-0_7][link]]] \\
  Assaf Marron, Irun R Cohen, *Guy Frankel*, David Harel, Smadar Szekely. MODELSWARD 2023.


- Emergent regulation of ant foraging frequency through a computationally inexpensive forager movement rule [[[https://elifesciences.org/articles/77659.pdf][link]]] \\
  *Guy Frankel*, Lior Baltiansky, Ofer Feinerman. eLife 2022.


** Workshop papers
- Syntax-Guided Synthesis with Counterexample-Guided E-graphs: A Work-in-Progress Report [[[https://ceur-ws.org/Vol-4008/SMT_paper11.pdf][link]]] \\
  *Guy Frankel*, Rudi Schneider, Michel Steuwer and Elizabeth Polgreen. SMT+PoS 2025.

This site is generated using Org mode's publishing system, inspired by
https://ogbe.net/blog/emacs_org_static_site.
